# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        path: node_modules/
        key: deps
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - run: ls -la
    - name: Publish to GitHub pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
          target_branch: gh-pages
          build_dir: build/
#           keep_history: true
          commit_message: Deploy to GitHub pages ${{ github.sha }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
